//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiexamen.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Retorno", Namespace="http://schemas.datacontract.org/2004/07/WsApiexamen.Modelo")]
    [System.SerializableAttribute()]
    public partial class Retorno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((this.RespuestaField.Equals(value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblExamen", Namespace="http://schemas.datacontract.org/2004/07/WsApiexamen.Modelo")]
    [System.SerializableAttribute()]
    public partial class tblExamen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idExamenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idExamen {
            get {
                return this.idExamenField;
            }
            set {
                if ((this.idExamenField.Equals(value) != true)) {
                    this.idExamenField = value;
                    this.RaisePropertyChanged("idExamen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IExamenServ")]
    public interface IExamenServ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamenServ/AgregarExamen", ReplyAction="http://tempuri.org/IExamenServ/AgregarExamenResponse")]
        apiexamen.ServiceReference1.Retorno AgregarExamen(string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamenServ/AgregarExamen", ReplyAction="http://tempuri.org/IExamenServ/AgregarExamenResponse")]
        System.Threading.Tasks.Task<apiexamen.ServiceReference1.Retorno> AgregarExamenAsync(string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamenServ/ActualizarExamen", ReplyAction="http://tempuri.org/IExamenServ/ActualizarExamenResponse")]
        apiexamen.ServiceReference1.Retorno ActualizarExamen(int Id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamenServ/ActualizarExamen", ReplyAction="http://tempuri.org/IExamenServ/ActualizarExamenResponse")]
        System.Threading.Tasks.Task<apiexamen.ServiceReference1.Retorno> ActualizarExamenAsync(int Id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamenServ/EliminarExamen", ReplyAction="http://tempuri.org/IExamenServ/EliminarExamenResponse")]
        apiexamen.ServiceReference1.Retorno EliminarExamen(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamenServ/EliminarExamen", ReplyAction="http://tempuri.org/IExamenServ/EliminarExamenResponse")]
        System.Threading.Tasks.Task<apiexamen.ServiceReference1.Retorno> EliminarExamenAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamenServ/ConsultarExamen", ReplyAction="http://tempuri.org/IExamenServ/ConsultarExamenResponse")]
        apiexamen.ServiceReference1.tblExamen[] ConsultarExamen(string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamenServ/ConsultarExamen", ReplyAction="http://tempuri.org/IExamenServ/ConsultarExamenResponse")]
        System.Threading.Tasks.Task<apiexamen.ServiceReference1.tblExamen[]> ConsultarExamenAsync(string Nombre, string Descripcion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExamenServChannel : apiexamen.ServiceReference1.IExamenServ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExamenServClient : System.ServiceModel.ClientBase<apiexamen.ServiceReference1.IExamenServ>, apiexamen.ServiceReference1.IExamenServ {
        
        public ExamenServClient() {
        }
        
        public ExamenServClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExamenServClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamenServClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamenServClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public apiexamen.ServiceReference1.Retorno AgregarExamen(string Nombre, string Descripcion) {
            return base.Channel.AgregarExamen(Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task<apiexamen.ServiceReference1.Retorno> AgregarExamenAsync(string Nombre, string Descripcion) {
            return base.Channel.AgregarExamenAsync(Nombre, Descripcion);
        }
        
        public apiexamen.ServiceReference1.Retorno ActualizarExamen(int Id, string Nombre, string Descripcion) {
            return base.Channel.ActualizarExamen(Id, Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task<apiexamen.ServiceReference1.Retorno> ActualizarExamenAsync(int Id, string Nombre, string Descripcion) {
            return base.Channel.ActualizarExamenAsync(Id, Nombre, Descripcion);
        }
        
        public apiexamen.ServiceReference1.Retorno EliminarExamen(int Id) {
            return base.Channel.EliminarExamen(Id);
        }
        
        public System.Threading.Tasks.Task<apiexamen.ServiceReference1.Retorno> EliminarExamenAsync(int Id) {
            return base.Channel.EliminarExamenAsync(Id);
        }
        
        public apiexamen.ServiceReference1.tblExamen[] ConsultarExamen(string Nombre, string Descripcion) {
            return base.Channel.ConsultarExamen(Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task<apiexamen.ServiceReference1.tblExamen[]> ConsultarExamenAsync(string Nombre, string Descripcion) {
            return base.Channel.ConsultarExamenAsync(Nombre, Descripcion);
        }
    }
}
